import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const html = readFileSync("index.html", "utf8");
const app = readFileSync("app.js", "utf8");
const css = readFileSync("styles.css", "utf8");
const phoneFrame = readFileSync("assets/phone-frame.png");
const openingVideo = readFileSync("assets/opening.mp4");
const spec = readFileSync("docs/superpowers/specs/2026-05-08-chat-word-guessing-game-design.md", "utf8");
const plan = readFileSync("docs/superpowers/plans/2026-05-08-chat-word-guessing-game.md", "utf8");

assert.match(html, /<html lang="ko">/);
assert.match(html, /아, 그거 뭐라 그러더라/);
assert.match(html, /<script src="game-core\.js"><\/script>/);
assert.match(html, /<script src="app\.js"><\/script>/);

assert.match(app, /GameCore\.createGame/);
assert.match(app, /Math\.floor\(Math\.random\(\) \* 100000\)/);
assert.match(app, /GameCore\.submitGuess/);
assert.match(app, /requestAiReply/);
assert.match(app, /\/api\/ai-reply/);
assert.doesNotMatch(app, /OPENAI_API_KEY/);
assert.match(app, /mode-card/);
assert.match(app, /opening-screen/);
assert.match(app, /opening-video/);
assert.match(app, /assets\/opening\.mp4/);
assert.match(app, /attachOpeningTransition/);
assert.match(app, /phone-frame-scene--behind-opening/);
assert.match(app, /phone-frame-scene--revealed/);
assert.match(app, /addEventListener\("ended"/);
assert.match(app, /addEventListener\("error"/);
assert.match(app, /renderModePicker\(\{ withOpening: true \}\)/);
assert.match(app, /mode-icon/);
assert.match(app, /mode-icon-label/);
assert.match(app, /intro-title-image/);
assert.match(app, /assets\/intro-title\.png/);
assert.match(app, /home-dock/);
assert.match(app, /dock-icon/);
assert.match(app, /mode-descriptions/);
assert.match(app, /장난\? 장난은 계속 말해주마\./);
assert.match(app, /이게 진짜니까 딱 5번만 설명한다\./);
assert.match(app, /니가 5번 안에 맞출 수 있을까\?/);
assert.match(app, /계속 말해도 너는 못 맞출껄\?/);
assert.doesNotMatch(app, /item\.subtitle/);
assert.doesNotMatch(app, /<small>/);
assert.doesNotMatch(app, /OpenAI 말고도 일단/);
assert.doesNotMatch(app, /<h1>아, 그거 뭐라 그러더라<\/h1>/);
assert.match(app, /답답한 친구가<br \/>설명하는 걸 맞혀봐/);
assert.match(app, /challengeRecords/);
assert.match(app, /모르겠는데\?/);
assert.match(app, /답변 입력/);
assert.match(app, /data-action="hint"/);
assert.match(app, /data-action="answer"/);
assert.match(app, /input-panel/);
assert.match(app, /compositionstart/);
assert.match(app, /compositionend/);
assert.match(app, /normalize\("NFC"\)/);
assert.match(app, /enterkeyhint="send"/);
assert.match(app, /spellcheck="false"/);
assert.match(app, /chat-room/);
assert.match(app, /floating-choices/);
assert.match(app, /composer-bar/);
assert.match(app, /AI가 말하는 중/);
assert.match(app, /기억난 건/);
assert.doesNotMatch(app, /정답은/);
assert.match(app, /renderResultAction/);
assert.match(app, /renderFloatingChoices/);
assert.match(app, /renderComposer/);
assert.match(app, /renderControlDeck/);
assert.match(app, /control-deck/);
assert.match(app, /\$\{renderControlDeck\(\)\}/);
assert.match(app, /data-action="back"/);
assert.match(app, /data-action="next"/);
assert.match(app, /data-action="composer-answer"/);
assert.match(app, /어휘력이 좋은 지 나쁜 지 모르겠는 놈/);
assert.match(app, /header-meta/);
assert.match(app, /default-profile/);
assert.doesNotMatch(app, /<strong>\$\{GameCore\.getModeConfig\(game\.mode\)\.label\}<\/strong>/);

assert.match(css, /\.phone/);
assert.match(css, /\.phone-frame-scene/);
assert.match(css, /assets\/phone-frame\.png/);
assert.match(css, /\.app[\s\S]*background: #000000/);
assert.match(css, /\.opening-screen/);
assert.match(css, /\.opening-video/);
assert.match(css, /\.opening-screen--done \.opening-video/);
assert.match(css, /\.phone-frame-scene--behind-opening/);
assert.match(css, /\.phone-frame-scene--revealed/);
assert.match(css, /\.intro-phone[\s\S]*background: #f8f1df/);
assert.match(css, /\.intro-title-image/);
assert.match(css, /\.mode-grid[\s\S]*grid-template-columns: repeat\(4, 1fr\)/);
assert.match(css, /\.mode-grid[\s\S]*align-content: start/);
assert.match(css, /\.mode-grid[\s\S]*padding: 58px 2px 0/);
assert.match(css, /\.mode-card\.easy/);
assert.match(css, /\.mode-card\.challenge/);
assert.match(css, /\.mode-icon[\s\S]*width: 42px/);
assert.match(css, /\.mode-icon-label/);
assert.match(css, /\.mode-card[\s\S]*max-width: 48px/);
assert.doesNotMatch(css, /\.mode-icon-label small/);
assert.match(css, /\.mode-descriptions/);
assert.match(css, /\.mode-descriptions[\s\S]*margin: 76px 4px 0/);
assert.match(css, /\.mode-description[\s\S]*grid-template-columns: 72px 1fr/);
assert.match(css, /\.mode-description strong[\s\S]*color: #202124/);
assert.doesNotMatch(css, /\.mode-description\.easy strong/);
assert.doesNotMatch(css, /\.mode-description\.normal strong/);
assert.doesNotMatch(css, /\.mode-description\.hard strong/);
assert.doesNotMatch(css, /\.mode-description\.challenge strong/);
assert.match(css, /\.home-dock[\s\S]*margin-top: auto/);
assert.match(css, /\.home-dock/);
assert.match(css, /\.dock-icon/);
assert.match(css, /\.bubble\.ai/);
assert.match(css, /\.bubble\.player/);
assert.match(css, /\.input-panel/);
assert.match(css, /\.chat-room/);
assert.match(css, /\.floating-choices/);
assert.match(css, /\.composer-bar/);
assert.match(css, /\.control-deck/);
assert.match(css, /grid-template-rows: auto auto 1fr/);
assert.doesNotMatch(css, /grid-template-rows: auto auto 1fr auto/);
assert.match(css, /\.header-meta/);
assert.match(css, /\.default-profile/);
assert.match(css, /\.profile-head/);
assert.match(css, /\.profile-body/);
assert.match(css, /background: #b7d3e9/);
assert.match(css, /\.control-deck[\s\S]*position: absolute/);
assert.match(css, /\.control-deck[\s\S]*bottom: 0/);
assert.match(css, /\.control-deck[\s\S]*min-height: 146px/);
assert.match(css, /\.result-action/);
assert.match(css, /\.next-button/);
assert.match(css, /\.composer-bar[\s\S]*background: transparent/);
assert.match(css, /\.chat-log[\s\S]*padding: 18px 14px 246px/);
assert.doesNotMatch(css, /\.floating-choices[\s\S]*position: absolute/);
assert.match(css, /@media/);
assert.match(css, /height: 100dvh/);
assert.match(css, /background: none/);
assert.match(css, /place-items: stretch/);
assert.ok(phoneFrame.length > 100000);
assert.ok(openingVideo.length > 500000);
assert.ok(readFileSync("assets/intro-title.png").length > 10000);

assert.match(spec, /early turns/i);
assert.match(spec, /later turns/i);
assert.match(spec, /아니아니/);
assert.match(spec, /똑바로/);
assert.match(plan, /early turns/i);
assert.match(plan, /later turns/i);
assert.match(plan, /아니아니/);
assert.match(plan, /똑바로/);
assert.match(spec, /Do not say "정보"/);
assert.match(spec, /Do not say "힌트"/);
assert.match(plan, /Do not say "정보"/);
assert.match(plan, /Do not say "힌트"/);
assert.doesNotMatch(spec, /Pace information progressively/);
assert.doesNotMatch(plan, /more specific information/);
assert.match(spec, /Do not reuse the same clue/);
assert.match(spec, /short filler message/);
assert.match(plan, /Do not reuse the same clue/);
assert.match(plan, /short filler message/);

console.log("html static tests passed");
