import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const app = readFileSync("app.js", "utf8");
const core = readFileSync("game-core.js", "utf8");
const server = readFileSync("server.mjs", "utf8");
const gitignore = readFileSync(".gitignore", "utf8");
const envExample = readFileSync(".env.example", "utf8");
const setupGuide = readFileSync("OPENAI_SETUP.md", "utf8");
const renderYaml = readFileSync("render.yaml", "utf8");
const packageJson = JSON.parse(readFileSync("package.json", "utf8"));

assert.match(server, /OPENAI_API_KEY/);
assert.match(server, /cleanOpenAiApiKey/);
assert.match(server, /https:\/\/api\.openai\.com\/v1\/responses/);
assert.match(server, /Authorization/);
assert.match(server, /Bearer \$\{apiKey\}/);
assert.match(server, /output_text/);
assert.match(server, /\/api\/ai-word/);
assert.match(server, /handleAiWord/);
assert.match(server, /buildWordInstructions/);
assert.match(server, /usedAnswers/);
assert.match(server, /parseGeneratedWord/);
assert.doesNotMatch(server, /jsonResponse\(response, 500, \{ error: error\.message/);
assert.match(server, /Do not reuse the same clue/);
assert.match(server, /Every non-filler response must include one concrete clue/);
assert.match(server, /Do not sprinkle question marks/);
assert.match(server, /sanitizeQuestionMarks/);
assert.match(server, /fallbackClue/);
assert.match(server, /short filler/);
assert.match(server, /tip-of-the-tongue/);
assert.match(server, /"\.mp4": "video\/mp4"/);
assert.match(server, /0\.0\.0\.0/);
assert.match(server, /\/healthz/);
assert.match(server, /AI_RATE_LIMIT_MAX/);
assert.match(server, /AI_RATE_LIMIT_WINDOW_MS/);
assert.match(server, /Retry-After/);
assert.match(server, /x-forwarded-for/);

assert.match(app, /\/api\/ai-reply/);
assert.match(app, /requestAiReply/);
assert.match(app, /GameCore\.isCorrectGuess/);
assert.doesNotMatch(app, /OPENAI_API_KEY/);
assert.doesNotMatch(app, /api\.openai\.com/);
assert.doesNotMatch(core, /OPENAI_API_KEY/);
assert.doesNotMatch(core, /api\.openai\.com/);

assert.match(gitignore, /^\.env$/m);
assert.match(gitignore, /^node_modules$/m);
assert.match(envExample, /^OPENAI_API_KEY=$/m);
assert.match(envExample, /^OPENAI_MODEL=gpt-5\.2$/m);
assert.match(envExample, /^AI_RATE_LIMIT_WINDOW_MS=60000$/m);
assert.match(envExample, /^AI_RATE_LIMIT_MAX=20$/m);
assert.equal(packageJson.scripts.start, "node server.mjs");
assert.match(renderYaml, /type: web/);
assert.match(renderYaml, /runtime: node/);
assert.match(renderYaml, /startCommand: npm start/);
assert.match(renderYaml, /healthCheckPath: \/healthz/);
assert.match(renderYaml, /key: OPENAI_API_KEY\s+sync: false/s);
assert.match(setupGuide, /브라우저에 넣지 않습니다/);
assert.match(setupGuide, /절대 하지 말 것/);
assert.match(setupGuide, /\.env/);

console.log("server static tests passed");
